yacc_misplaced.py returned with 1

Traceback (most recent call last):
  ...
ply.yacc.YaccError: Unable to build parser

ERROR: /home/herczy/devel/ply/test/yacc_misplaced.py:32: Misplaced '|'
