yacc_badprec2.py returned with 1

Traceback (most recent call last):
  ...
ply.yacc.YaccError: Unable to build parser

ERROR: Bad precedence table
