lex_error2.py returned with 1

Traceback (most recent call last):
  ...
SyntaxError: Can't build lexer

ERROR: Rule 't_error' must be defined as a function
